"use client";

import { useState } from 'react';
import { useRouter } from 'next/navigation';
import api from '@/lib/api';
import Link from 'next/link';
import { BookOpen, CheckCircle, Copy, ArrowRight } from 'lucide-react';

export default function RegisterPage() {
    const [username, setUsername] = useState('');
    const [email, setEmail] = useState('');
    const [password, setPassword] = useState('');
    const [passwordStrength, setPasswordStrength] = useState({ score: 0, label: 'Very Weak', color: 'bg-slate-200' });
    const [error, setError] = useState('');
    const [successData, setSuccessData] = useState<any>(null);
    const [isLoading, setIsLoading] = useState(false);
    const [copied, setCopied] = useState(false);
    const router = useRouter();
    const [showPassword, setShowPassword] = useState(false);

    const checkPasswordStrength = (pass: string) => {
        let score = 0;
        if (pass.length > 7) score++;
        if (/[A-Z]/.test(pass)) score++;
        if (/[a-z]/.test(pass)) score++;
        if (/[0-9]/.test(pass)) score++;
        if (/[^A-Za-z0-9]/.test(pass)) score++;

        const labels = ['Very Weak', 'Weak', 'Fair', 'Strong', 'Very Strong'];
        const colors = ['bg-red-500', 'bg-orange-500', 'bg-yellow-500', 'bg-emerald-500', 'bg-indigo-600'];
        
        setPasswordStrength({
            score,
            label: pass.length === 0 ? 'Empty' : labels[Math.min(score, 4)],
            color: pass.length === 0 ? 'bg-slate-200' : colors[Math.min(score, 4)]
        });
    };

    const handleRegister = async (e: React.FormEvent) => {
        e.preventDefault();
        setError('');
        setSuccessData(null);
        setIsLoading(true);
        try {
            // We only send username and email, role is STUDENT by default on backend
            // Password will be generated by backend
            const res = await api.post('users/register/', {
                username,
                email,
                password
            });
            setSuccessData(res.data);
        } catch (err: any) {
            setError(err.response?.data?.username?.[0] || err.response?.data?.email?.[0] || 'Registration failed. Please try again.');
        } finally {
            setIsLoading(false);
        }
    };

    const copyPassword = () => {
        if (successData?.password) {
            navigator.clipboard.writeText(successData.password);
            setCopied(true);
            setTimeout(() => setCopied(false), 2000);
        }
    };

    if (successData) {
        return (
            <div className="min-h-screen bg-slate-50 flex flex-col justify-center py-12 sm:px-6 lg:px-8 font-sans">
                <div className="sm:mx-auto sm:w-full sm:max-w-md">
                    <div className="bg-white py-10 px-8 shadow-2xl shadow-slate-200/50 sm:rounded-3xl border border-slate-100 text-center">
                        <div className="w-16 h-16 bg-emerald-100 text-emerald-600 rounded-full flex items-center justify-center mx-auto mb-6">
                            <CheckCircle className="w-10 h-10" />
                        </div>
                        <h2 className="text-3xl font-bold text-slate-900 mb-2">Registration Successful!</h2>
                        <p className="text-slate-600 mb-8">Your student account has been created. Please save your login details securely.</p>

                        <div className="bg-slate-50 rounded-2xl p-6 border border-slate-200 text-left mb-8">
                            <div className="mb-4">
                                <label className="block text-xs font-bold text-slate-400 uppercase tracking-wider mb-1">Username</label>
                                <p className="text-slate-900 font-semibold">{successData.username}</p>
                            </div>
                            <div>
                                <label className="block text-xs font-bold text-slate-400 uppercase tracking-wider mb-1">Generated Password</label>
                                <div className="flex items-center justify-between bg-white border border-slate-200 rounded-xl p-3 mt-1">
                                    <code className="text-indigo-600 font-mono font-bold text-lg">{successData.password}</code>
                                    <button
                                        onClick={copyPassword}
                                        className="p-2 hover:bg-slate-50 rounded-lg transition-colors text-slate-400 hover:text-indigo-600"
                                        title="Copy to clipboard"
                                    >
                                        {copied ? <CheckCircle className="w-5 h-5 text-emerald-500" /> : <Copy className="w-5 h-5" />}
                                    </button>
                                </div>
                            </div>
                        </div>

                        <Link
                            href="/login"
                            className="w-full flex items-center justify-center gap-2 py-4 px-6 bg-indigo-600 hover:bg-indigo-700 text-white rounded-2xl font-bold transition-all shadow-lg shadow-indigo-200 text-lg group"
                        >
                            Go to Login
                            <ArrowRight className="w-5 h-5 group-hover:translate-x-1 transition-transform" />
                        </Link>
                    </div>
                </div>
            </div>
        );
    }

    return (
        <div className="min-h-screen bg-slate-50 flex flex-col justify-center py-12 sm:px-6 lg:px-8 font-sans">
            <div className="sm:mx-auto sm:w-full sm:max-w-md flex flex-col items-center">
                <Link href="/" className="flex items-center gap-2 mb-6 hover:opacity-80 transition-opacity">
                    <div className="bg-indigo-600 p-2 rounded-lg text-white font-bold">L</div>
                    <span className="font-bold text-3xl tracking-tight text-slate-900">LMSphere</span>
                </Link>
                <h2 className="mt-2 text-center text-3xl font-extrabold text-slate-900">
                    Student Registration
                </h2>
                <p className="mt-2 text-center text-sm text-slate-600">
                    Fill in your details to get your login ID and password.
                </p>
            </div>

            <div className="mt-8 sm:mx-auto sm:w-full sm:max-w-md">
                <div className="bg-white py-8 px-4 shadow-xl shadow-slate-200/50 sm:rounded-2xl sm:px-10 border border-slate-100">
                    {error && (
                        <div className="mb-6 p-4 rounded-lg bg-red-50 border border-red-100 text-red-600 text-sm font-medium">
                            {error}
                        </div>
                    )}

                    <form className="space-y-6" onSubmit={handleRegister}>
                        <div>
                            <label htmlFor="username" className="block text-sm font-medium text-slate-700">
                                Desired Username
                            </label>
                            <div className="mt-1">
                                <input
                                    id="username"
                                    name="username"
                                    type="text"
                                    required
                                    value={username}
                                    onChange={(e) => setUsername(e.target.value)}
                                    className="appearance-none block w-full px-4 py-3 border border-slate-300 rounded-xl shadow-sm placeholder-slate-400 focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 sm:text-sm text-slate-900 transition-colors bg-slate-50 focus:bg-white"
                                    placeholder="e.g. johndoe123"
                                />
                            </div>
                        </div>

                        <div>
                            <label htmlFor="email" className="block text-sm font-medium text-slate-700">
                                Email address
                            </label>
                            <div className="mt-1">
                                <input
                                    id="email"
                                    name="email"
                                    type="email"
                                    required
                                    value={email}
                                    onChange={(e) => setEmail(e.target.value)}
                                    className="appearance-none block w-full px-4 py-3 border border-slate-300 rounded-xl shadow-sm placeholder-slate-400 focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 sm:text-sm text-slate-900 transition-colors bg-slate-50 focus:bg-white"
                                    placeholder="you@example.com"
                                />
                            </div>
                        </div>

                        <div>
                            <label htmlFor="password" className="block text-sm font-medium text-slate-700 mb-1">
                                Password
                            </label>
                            <div className="relative">
                                <input
                                    id="password"
                                    name="password"
                                    type={showPassword ? "text" : "password"}
                                    required
                                    value={password}
                                    onChange={(e) => {
                                        setPassword(e.target.value);
                                        checkPasswordStrength(e.target.value);
                                    }}
                                    className="appearance-none block w-full px-4 py-3 border border-slate-300 rounded-xl shadow-sm placeholder-slate-400 focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 sm:text-sm text-slate-900 transition-colors bg-slate-50 focus:bg-white pr-12"
                                    placeholder="Min. 8 characters"
                                />
                                <button
                                    type="button"
                                    onClick={() => setShowPassword(!showPassword)}
                                    className="absolute right-3 top-1/2 -translate-y-1/2 text-slate-400 hover:text-slate-600 text-xs font-bold"
                                >
                                    {showPassword ? "HIDE" : "SHOW"}
                                </button>
                            </div>
                            
                            {/* Strength Meter */}
                            <div className="mt-3">
                                <div className="flex justify-between items-center mb-1">
                                    <span className="text-[10px] font-bold text-slate-400 uppercase tracking-tighter">Security Level</span>
                                    <span className={`text-[10px] font-bold px-1.5 py-0.5 rounded uppercase ${passwordStrength.color} text-white transition-all`}>
                                        {passwordStrength.label}
                                    </span>
                                </div>
                                <div className="h-1.5 w-full bg-slate-100 rounded-full overflow-hidden flex gap-0.5">
                                    {[1, 2, 3, 4, 5].map((step) => (
                                        <div 
                                            key={step}
                                            className={`h-full flex-grow transition-all duration-500 ${step <= passwordStrength.score ? passwordStrength.color : 'bg-slate-200 opacity-20'}`}
                                        />
                                    ))}
                                </div>
                                <ul className="mt-2 space-y-1">
                                    <li className={`text-[10px] flex items-center gap-1 ${password.length >= 8 ? 'text-emerald-500' : 'text-slate-400'}`}>
                                        <div className={`w-1 h-1 rounded-full ${password.length >= 8 ? 'bg-emerald-500' : 'bg-slate-300'}`} />
                                        At least 8 characters
                                    </li>
                                    <li className={`text-[10px] flex items-center gap-1 ${/[0-9]/.test(password) && /[^A-Za-z0-9]/.test(password) ? 'text-emerald-500' : 'text-slate-400'}`}>
                                        <div className={`w-1 h-1 rounded-full ${/[0-9]/.test(password) && /[^A-Za-z0-9]/.test(password) ? 'bg-emerald-500' : 'bg-slate-300'}`} />
                                        Numbers & Special characters
                                    </li>
                                </ul>
                            </div>
                        </div>

                        <div>
                            <button
                                type="submit"
                                disabled={isLoading}
                                className="w-full h-12 flex justify-center items-center py-3 px-4 border border-transparent rounded-xl shadow-lg text-sm font-bold text-white bg-indigo-600 hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500 transition-all disabled:opacity-70"
                            >
                                {isLoading ? "Processing..." : "Register Now"}
                            </button>
                        </div>
                    </form>

                    <div className="mt-8 text-center">
                        <p className="text-sm text-slate-500">
                            Already have an account? <Link href="/login" className="text-indigo-600 font-bold hover:underline">Log in</Link>
                        </p>
                    </div>
                </div>
            </div>
        </div>
    );
}
