"use client";

import { useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import Cookies from "js-cookie";
import { motion, AnimatePresence } from "framer-motion";
import api from "@/lib/api";
import DarkModeToggle from "@/components/DarkModeToggle";
import {
  Shield, Users, UserPlus, GraduationCap, BookOpen, Copy,
  LogOut, Plus, Trash2, Check, Key, UserCheck, Link as LinkIcon,
  Edit3, Eye, EyeOff, X, Upload, FileUp, RefreshCw
} from "lucide-react";

const TABS = ["Users", "Add Instructor", "Add Student", "Bulk Upload", "Courses", "Assign Course"];
const TAB_ICONS: any = {
  "Users": <Users className="w-4 h-4" />,
  "Add Instructor": <UserPlus className="w-4 h-4" />,
  "Add Student": <GraduationCap className="w-4 h-4" />,
  "Bulk Upload": <Upload className="w-4 h-4" />,
  "Courses": <BookOpen className="w-4 h-4" />,
  "Assign Course": <LinkIcon className="w-4 h-4" />,
};

interface Credential { username: string; email: string; password: string; role: string; }

export default function AdminDashboard() {
  const router = useRouter();
  const [user, setUser] = useState<any>(null);
  const [activeTab, setActiveTab] = useState("Users");

  const [users, setUsers] = useState<any[]>([]);
  const [courses, setCourses] = useState<any[]>([]);
  const [enrollments, setEnrollments] = useState<any[]>([]);

  // Credential display after creation
  const [newCredential, setNewCredential] = useState<Credential | null>(null);
  const [copied, setCopied] = useState(false);

  // Add Instructor form
  const [instForm, setInstForm] = useState({ username: "", full_name: "", email: "", phone: "", assigned_courses: [] as number[] });
  // Add Student form
  const [studForm, setStudForm] = useState({ username: "", full_name: "", email: "", phone: "", assigned_courses: [] as number[] });
  // Add Course form
  const [courseForm, setCourseForm] = useState({ title: "", description: "", instructor: "" });
  // Assign course form
  const [assignForm, setAssignForm] = useState({ course: "", student: "" });

  const [submitting, setSubmitting] = useState(false);

  // Edit & Assign state
  const [editUser, setEditUser] = useState<any>(null);
  const [editForm, setEditForm] = useState({ full_name: "", email: "", phone: "", is_active: true });
  const [bulkFile, setBulkFile] = useState<File | null>(null);
  const [bulkRole, setBulkRole] = useState("STUDENT");
  const [assigningUser, setAssigningUser] = useState<any>(null);
  const [assignCourseIds, setAssignCourseIds] = useState<number[]>([]);
  const [showPassFor, setShowPassFor] = useState<number | null>(null);

  // Quick View states
  const [viewingUser, setViewingUser] = useState<any>(null);
  const [viewingCourse, setViewingCourse] = useState<any>(null);

  const fetchData = async () => {
    try {
      const [uRes, cRes, eRes] = await Promise.all([
        api.get("users/manage/"),
        api.get("courses/"),
        api.get("enrollments/"),
      ]);
      setUsers(uRes.data);
      setCourses(cRes.data);
      setEnrollments(eRes.data);
    } catch (err) { console.error(err); }
  };

  useEffect(() => {
    const init = async () => {
      try {
        const res = await api.get("users/me/");
        if (res.data.role !== "ADMIN") router.push("/login");
        else { setUser(res.data); fetchData(); }
      } catch { router.push("/login"); }
    };
    init();
  }, [router]);

  const handleLogout = () => {
    Cookies.remove("access_token"); Cookies.remove("refresh_token"); Cookies.remove("user_role");
    router.push("/login");
  };

  // Add Instructor — Admin exclusive
  const handleAddInstructor = async (e: React.FormEvent) => {
    e.preventDefault(); setSubmitting(true); setNewCredential(null);
    try {
      const res = await api.post("users/manage/", { ...instForm, role: "INSTRUCTOR" });
      // username is auto-generated by the backend
      setNewCredential({
        username: res.data.user.username,
        email: res.data.user.email,
        password: res.data.user.password,
        role: "INSTRUCTOR"
      });
      setInstForm({ username: "", full_name: "", email: "", phone: "", assigned_courses: [] });
      fetchData();
    } catch (err: any) {
      alert(err.response?.data?.email?.[0] || "Error creating instructor.");
    }
    setSubmitting(false);
  };

  // Add Student — Admin exclusive
  const handleAddStudent = async (e: React.FormEvent) => {
    e.preventDefault(); setSubmitting(true); setNewCredential(null);
    try {
      const res = await api.post("users/manage/", { ...studForm, role: "STUDENT" });
      // username is auto-generated by the backend
      setNewCredential({
        username: res.data.user.username,
        email: res.data.user.email,
        password: res.data.user.password,
        role: "STUDENT"
      });
      setStudForm({ username: "", full_name: "", email: "", phone: "", assigned_courses: [] });
      fetchData();
    } catch (err: any) {
      alert(err.response?.data?.email?.[0] || "Error creating student.");
    }
    setSubmitting(false);
  };

  // Add Course — Admin exclusive, assigns to instructor
  const handleAddCourse = async (e: React.FormEvent) => {
    e.preventDefault(); setSubmitting(true);
    try {
      await api.post("courses/", courseForm);
      setCourseForm({ title: "", description: "", instructor: "" });
      fetchData(); alert("Course created and assigned to instructor!");
    } catch { alert("Error creating course."); }
    setSubmitting(false);
  };

  // Assign student to course — Admin exclusive
  const handleAssignCourse = async (e: React.FormEvent) => {
    e.preventDefault(); setSubmitting(true);
    try {
      await api.post("enrollments/", { course: assignForm.course, student: assignForm.student, progress: 0 });
      setAssignForm({ course: "", student: "" });
      fetchData(); alert("Student successfully enrolled in course!");
    } catch (err: any) {
      alert(err.response?.data?.non_field_errors?.[0] || "Error enrolling. Already enrolled?");
    }
    setSubmitting(false);
  };

  const handleDeleteUser = async (id: number) => {
    if (confirm("Delete this user permanently?")) {
      try { await api.delete(`users/manage/${id}/`); fetchData(); }
      catch { alert("Error deleting user."); }
    }
  };

  const handleEditUser = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!editUser) return;
    try {
      await api.patch(`users/manage/${editUser.id}/`, editForm);
      setEditUser(null);
      fetchData();
    } catch { alert("Error updating user."); }
  };

  const handleAssignCourses = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!assigningUser) return;
    try {
      if (assigningUser.role === 'INSTRUCTOR') {
        await Promise.all(assignCourseIds.map(cid =>
          api.patch(`courses/${cid}/`, { instructor: assigningUser.id })
        ));
      } else {
        await Promise.all(assignCourseIds.map(cid =>
          api.post('enrollments/', { course: cid, student: assigningUser.id, progress: 0 }).catch(() => {})
        ));
      }
      setAssigningUser(null); setAssignCourseIds([]);
      fetchData(); alert('Courses assigned successfully!');
    } catch { alert('Error assigning courses.'); }
  };

  const handleResetPassword = async (id: number) => {
    if (confirm("Reset this user's password and send them an email?")) {
      try {
        const res = await api.post(`users/manage/${id}/reset-password/`);
        alert(`Success! New password: ${res.data.new_password}. Email status: ${res.data.email_sent ? 'Sent' : 'Failed to send'}`);
        fetchData();
      } catch { alert("Error resetting password."); }
    }
  };

  const handleBulkUpload = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!bulkFile) return alert("Select a CSV file first.");
    setSubmitting(true);
    const formData = new FormData();
    formData.append("file", bulkFile);
    formData.append("role", bulkRole);
    try {
      const res = await api.post("users/manage/bulk-upload/", formData);
      alert(res.data.message);
      if (res.data.errors.length > 0) console.error("Bulk Upload Errors:", res.data.errors);
      setBulkFile(null);
      fetchData();
    } catch { alert("Error uploading CSV."); }
    setSubmitting(false);
  };

  const copyCredentials = (cred: Credential) => {
    navigator.clipboard.writeText(`Username: ${cred.username}\nEmail: ${cred.email}\nPassword: ${cred.password}\nRole: ${cred.role}`);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  if (!user) return (
    <div className="min-h-screen flex items-center justify-center">
      <div className="w-10 h-10 border-4 border-primary/30 border-t-primary rounded-full animate-spin" />
    </div>
  );

  const instructors = users.filter((u: any) => u.role === "INSTRUCTOR");
  const students = users.filter((u: any) => u.role === "STUDENT");
  const fieldClass = "w-full px-4 py-2.5 rounded-xl border border-border bg-secondary/30 text-sm focus:outline-none focus:ring-2 focus:ring-primary/30 transition-all";
  const btnClass = "w-full py-2.5 bg-primary text-white text-sm font-bold rounded-xl hover:bg-primary/90 transition-all flex items-center justify-center gap-2 disabled:opacity-60";

  return (
    <div className="min-h-screen px-4 py-8 md:px-8">
      <div className="max-w-7xl mx-auto">

        {/* Header */}
        <motion.header initial={{ opacity: 0, y: -20 }} animate={{ opacity: 1, y: 0 }}
          className="flex items-center justify-between mb-8 p-4 glass rounded-2xl border border-border">
          <div className="flex items-center gap-3">
            <div className="p-2 bg-red-500/20 rounded-xl"><Shield className="w-6 h-6 text-red-500" /></div>
            <div>
              <h1 className="font-bold text-lg">Admin Control Panel</h1>
              <p className="text-xs text-foreground/60">Full system access — <span className="text-red-500 font-semibold">{user.username}</span></p>
            </div>
          </div>
          <div className="flex items-center gap-2">
            <DarkModeToggle />
            <button onClick={handleLogout} className="flex items-center gap-2 px-4 py-2 text-sm font-semibold rounded-xl border border-border hover:bg-secondary/60 transition-all">
              <LogOut className="w-4 h-4" /> Logout
            </button>
          </div>
        </motion.header>

        {/* Stats */}
        <div className="grid grid-cols-2 md:grid-cols-4 gap-4 mb-8">
          {[
            { label: "Total Users", value: users.length, icon: <Users className="w-5 h-5 text-primary" />, color: "from-primary/10" },
            { label: "Instructors", value: instructors.length, icon: <UserPlus className="w-5 h-5 text-blue-500" />, color: "from-blue-500/10" },
            { label: "Students", value: students.length, icon: <GraduationCap className="w-5 h-5 text-green-500" />, color: "from-green-500/10" },
            { label: "Total Courses", value: courses.length, icon: <BookOpen className="w-5 h-5 text-accent" />, color: "from-accent/10" },
          ].map((s, i) => (
            <motion.div key={i} whileHover={{ y: -3 }}
              className={`bg-card border border-border rounded-2xl p-4 bg-gradient-to-br ${s.color} to-transparent`}>
              <div className="flex items-center gap-2 mb-1">{s.icon}<span className="text-xs text-foreground/60">{s.label}</span></div>
              <div className="text-2xl font-black">{s.value}</div>
            </motion.div>
          ))}
        </div>

        {/* Tabs */}
        <div className="flex items-center gap-2 overflow-x-auto pb-2 mb-6">
          {TABS.map(tab => (
            <button key={tab} onClick={() => { setActiveTab(tab); setNewCredential(null); }}
              className={`flex items-center gap-2 px-4 py-2.5 rounded-xl text-sm font-semibold whitespace-nowrap transition-all ${
                activeTab === tab ? "bg-primary text-white shadow-lg shadow-primary/30" : "bg-card border border-border hover:bg-secondary/50 text-foreground/70"
              }`}>
              {TAB_ICONS[tab]}{tab}
            </button>
          ))}
        </div>

        <AnimatePresence mode="wait">
          <motion.div key={activeTab} initial={{ opacity: 0, y: 10 }} animate={{ opacity: 1, y: 0 }} exit={{ opacity: 0, y: -10 }} transition={{ duration: 0.2 }}>

            {/* ===== USERS TAB ===== */}
            {activeTab === "Users" && (
              <div className="grid md:grid-cols-2 gap-6">
                {/* Instructors List */}
                <div className="bg-card border border-border rounded-2xl overflow-hidden">
                  <div className="px-5 py-4 border-b border-border bg-blue-500/5 flex items-center gap-2">
                    <UserPlus className="w-4 h-4 text-blue-500" />
                    <h2 className="font-bold text-sm">Instructors ({instructors.length})</h2>
                  </div>
                  <div className="divide-y divide-border max-h-96 overflow-y-auto">
                    {instructors.length === 0 && <p className="p-6 text-sm text-foreground/50 text-center italic">No instructors yet. Add one below.</p>}
                    {instructors.map((u: any) => (
                      <motion.div key={u.id} className="flex items-center gap-3 px-5 py-3 hover:bg-secondary/30 transition-colors">
                        <div className="w-8 h-8 rounded-full bg-blue-500/20 text-blue-500 font-bold text-xs flex items-center justify-center uppercase flex-shrink-0">
                          {u.username[0]}
                        </div>
                        <div className="flex-grow min-w-0">
                          <button onClick={() => setViewingUser(u)} className="font-semibold text-sm truncate hover:text-primary transition-colors block text-left w-full">
                            {u.full_name || u.username}
                          </button>
                          <div className="flex flex-col gap-0.5 mt-0.5">
                            <p className="text-[10px] font-bold text-primary flex items-center gap-1">
                              ID: <span className="bg-primary/10 px-1 rounded uppercase">{u.username}</span>
                            </p>
                            <p className="text-[10px] font-bold text-foreground/40 flex items-center gap-1">
                              PW: <span className="bg-secondary/50 px-1 rounded font-mono">{u.plain_password || '********'}</span>
                            </p>
                          </div>
                        </div>
                        <div className="flex items-center gap-1.5 flex-shrink-0">
                          <button onClick={() => setViewingUser(u)} className="text-primary hover:bg-primary/10 p-1.5 rounded-lg transition-all" title="View Details">
                            <Eye className="w-3.5 h-3.5" />
                          </button>
                          <button onClick={() => handleDeleteUser(u.id)} className="text-red-400 hover:text-red-600 p-1.5 rounded-lg hover:bg-red-50 dark:hover:bg-red-900/20 transition-all">
                            <Trash2 className="w-3.5 h-3.5" />
                          </button>
                        </div>
                      </motion.div>
                    ))}
                  </div>
                </div>

                {/* Students List */}
                <div className="bg-card border border-border rounded-2xl overflow-hidden">
                  <div className="px-5 py-4 border-b border-border bg-green-500/5 flex items-center gap-2">
                    <GraduationCap className="w-4 h-4 text-green-500" />
                    <h2 className="font-bold text-sm">Students ({students.length})</h2>
                  </div>
                  <div className="divide-y divide-border max-h-96 overflow-y-auto">
                    {students.length === 0 && <p className="p-6 text-sm text-foreground/50 text-center italic">No students yet.</p>}
                    {students.map((u: any) => {
                      const enrolled = enrollments.filter((e: any) => e.student === u.id).length;
                      return (
                        <motion.div key={u.id} className="flex items-center gap-3 px-5 py-3 hover:bg-secondary/30 transition-colors">
                          <div className="w-8 h-8 rounded-full bg-green-500/20 text-green-500 font-bold text-xs flex items-center justify-center uppercase flex-shrink-0">
                            {u.username[0]}
                          </div>
                          <div className="flex-grow min-w-0">
                            <button onClick={() => setViewingUser(u)} className="font-semibold text-sm truncate hover:text-green-500 transition-colors block text-left w-full">
                              {u.full_name || u.username}
                            </button>
                            <div className="flex flex-col gap-0.5 mt-0.5">
                              <p className="text-[10px] font-bold text-green-600 flex items-center gap-1">
                                ID: <span className="bg-green-500/10 px-1 rounded uppercase">{u.username}</span>
                              </p>
                              <p className="text-[10px] font-bold text-foreground/40 flex items-center gap-1">
                                PW: <span className="bg-secondary/50 px-1 rounded font-mono">{u.plain_password || '********'}</span>
                              </p>
                            </div>
                          </div>
                          <div className="flex items-center gap-1.5 flex-shrink-0">
                            <span className={`text-[10px] font-black uppercase px-2 py-0.5 rounded-full ${u.is_active ? 'bg-green-500/10 text-green-500' : 'bg-red-500/10 text-red-500'}`}>
                                {u.is_active ? 'Active' : 'Inactive'}
                            </span>
                            <button onClick={() => { setEditUser(u); setEditForm({ full_name: u.full_name || '', email: u.email, phone: u.phone || '', is_active: u.is_active }); }} className="text-blue-500 p-1.5 rounded-lg hover:bg-blue-50 transition-all"><Edit3 className="w-3.5 h-3.5" /></button>
                            <button onClick={() => handleResetPassword(u.id)} className="text-orange-500 p-1.5 rounded-lg hover:bg-orange-50 transition-all"><RefreshCw className="w-3.5 h-3.5" /></button>
                            <button onClick={() => handleDeleteUser(u.id)} className="text-red-400 hover:text-red-600 p-1.5 rounded-lg hover:bg-red-50 transition-all"><Trash2 className="w-3.5 h-3.5" /></button>
                          </div>
                        </motion.div>
                      );
                    })}
                  </div>
                </div>
              </div>
            )}

            {/* ===== ADD INSTRUCTOR ===== */}
            {activeTab === "Add Instructor" && (
              <div className="max-w-md">
                <div className="bg-card border border-border rounded-2xl p-6 mb-4">
                  <h2 className="font-bold text-lg mb-1 flex items-center gap-2">
                    <UserPlus className="w-5 h-5 text-primary" />Add Instructor
                  </h2>
                  <p className="text-xs text-foreground/60 mb-5">A secure password is automatically generated and displayed once.</p>
                  <form onSubmit={handleAddInstructor} className="space-y-3">
                    <input className={fieldClass} placeholder="Full Name (e.g. Dr. Ahmed Khan)" value={instForm.full_name} onChange={e => setInstForm(p => ({ ...p, full_name: e.target.value }))} required />
                    <input type="email" className={fieldClass} placeholder="Email address" value={instForm.email} onChange={e => setInstForm(p => ({ ...p, email: e.target.value }))} required />
                    <input type="tel" className={fieldClass} placeholder="Phone number (optional)" value={instForm.phone} onChange={e => setInstForm(p => ({ ...p, phone: e.target.value }))} />
                    <p className="text-xs text-accent font-semibold px-1">✨ Instructor ID &amp; Password are auto-generated by the system</p>
                    <div>
                      <label className="text-xs text-foreground/60 mb-1.5 block">Assign Courses (optional — hold Ctrl to multi-select)</label>
                      <select multiple className={`${fieldClass} min-h-24`}
                        onChange={e => setInstForm(p => ({ ...p, assigned_courses: Array.from(e.target.selectedOptions, o => Number(o.value)) }))}>
                        {courses.map((c: any) => <option key={c.id} value={c.id}>{c.title}</option>)}
                      </select>
                    </div>
                    <button type="submit" className={btnClass} disabled={submitting}>
                      <Key className="w-4 h-4" />Create Instructor Account
                    </button>
                  </form>
                </div>

                {/* Credential Display */}
                <AnimatePresence>
                  {newCredential && (
                    <motion.div initial={{ opacity: 0, y: 10 }} animate={{ opacity: 1, y: 0 }} exit={{ opacity: 0 }}
                      className="bg-gradient-to-br from-primary/10 to-accent/5 border-2 border-primary/30 rounded-2xl p-5">
                      <div className="flex items-center justify-between mb-4">
                        <div className="flex items-center gap-2">
                          <UserCheck className="w-5 h-5 text-green-500" />
                          <span className="font-bold text-green-600 text-sm">Account Created!</span>
                        </div>
                        <button onClick={() => copyCredentials(newCredential)}
                          className="flex items-center gap-1.5 text-xs font-semibold px-3 py-1.5 rounded-lg bg-primary/10 text-primary hover:bg-primary hover:text-white transition-all">
                          {copied ? <Check className="w-3 h-3" /> : <Copy className="w-3 h-3" />}
                          {copied ? "Copied!" : "Copy All"}
                        </button>
                      </div>
                      <div className="space-y-2">
                        {[
                          { label: "Username", value: newCredential.username },
                          { label: "Email", value: newCredential.email },
                          { label: "Role", value: newCredential.role },
                          { label: "Password", value: newCredential.password },
                        ].map(row => (
                          <div key={row.label} className="flex items-center justify-between p-2.5 bg-background rounded-xl border border-border">
                            <span className="text-xs text-foreground/50 font-semibold uppercase tracking-wide w-20 flex-shrink-0">{row.label}</span>
                            <code className="text-sm font-mono font-bold text-foreground truncate ml-2">{row.value}</code>
                          </div>
                        ))}
                      </div>
                      <p className="text-xs text-orange-500 mt-3 font-medium">⚠️ Save these credentials now — the password will not be shown again.</p>
                    </motion.div>
                  )}
                </AnimatePresence>
              </div>
            )}

            {/* ===== ADD STUDENT ===== */}
            {activeTab === "Add Student" && (
              <div className="max-w-md">
                <div className="bg-card border border-border rounded-2xl p-6 mb-4">
                  <h2 className="font-bold text-lg mb-1 flex items-center gap-2">
                    <GraduationCap className="w-5 h-5 text-green-500" />Add Student
                  </h2>
                  <p className="text-xs text-foreground/60 mb-5">Creates a student account with an auto-generated secure password.</p>
                  <form onSubmit={handleAddStudent} className="space-y-3">
                    <input className={fieldClass} placeholder="Full Name (e.g. Ali Hassan)" value={studForm.full_name} onChange={e => setStudForm(p => ({ ...p, full_name: e.target.value }))} required />
                    <input className={fieldClass} placeholder="Username / Login ID (e.g. student_ali)" value={studForm.username} onChange={e => setStudForm(p => ({ ...p, username: e.target.value }))} required />
                    <input type="email" className={fieldClass} placeholder="Email address" value={studForm.email} onChange={e => setStudForm(p => ({ ...p, email: e.target.value }))} required />
                    <input type="tel" className={fieldClass} placeholder="Phone number (optional)" value={studForm.phone} onChange={e => setStudForm(p => ({ ...p, phone: e.target.value }))} />
                    <div>
                      <label className="text-xs text-foreground/60 mb-1.5 block">Enroll in Courses (optional — hold Ctrl to multi-select)</label>
                      <select multiple className={`${fieldClass} min-h-24`}
                        onChange={e => setStudForm(p => ({ ...p, assigned_courses: Array.from(e.target.selectedOptions, o => Number(o.value)) }))}>
                        {courses.map((c: any) => <option key={c.id} value={c.id}>{c.title}</option>)}
                      </select>
                    </div>
                    <button type="submit" className="w-full py-2.5 bg-green-600 text-white text-sm font-bold rounded-xl hover:bg-green-700 transition-all flex items-center justify-center gap-2 disabled:opacity-60" disabled={submitting}>
                      <Key className="w-4 h-4" />Create Student Account
                    </button>
                  </form>
                </div>

                <AnimatePresence>
                  {newCredential && (
                    <motion.div initial={{ opacity: 0, y: 10 }} animate={{ opacity: 1, y: 0 }} exit={{ opacity: 0 }}
                      className="bg-gradient-to-br from-green-500/10 to-emerald-500/5 border-2 border-green-500/30 rounded-2xl p-5">
                      <div className="flex items-center justify-between mb-4">
                        <div className="flex items-center gap-2">
                          <UserCheck className="w-5 h-5 text-green-500" />
                          <span className="font-bold text-green-600 text-sm">Student Account Created!</span>
                        </div>
                        <button onClick={() => copyCredentials(newCredential)}
                          className="flex items-center gap-1.5 text-xs font-semibold px-3 py-1.5 rounded-lg bg-green-500/10 text-green-600 hover:bg-green-500 hover:text-white transition-all">
                          {copied ? <Check className="w-3 h-3" /> : <Copy className="w-3 h-3" />}
                          {copied ? "Copied!" : "Copy All"}
                        </button>
                      </div>
                      <div className="space-y-2">
                        {[
                          { label: "Username", value: newCredential.username },
                          { label: "Email", value: newCredential.email },
                          { label: "Role", value: newCredential.role },
                          { label: "Password", value: newCredential.password },
                        ].map(row => (
                          <div key={row.label} className="flex items-center justify-between p-2.5 bg-background rounded-xl border border-border">
                            <span className="text-xs text-foreground/50 font-semibold uppercase tracking-wide w-20 flex-shrink-0">{row.label}</span>
                            <code className="text-sm font-mono font-bold text-foreground truncate ml-2">{row.value}</code>
                          </div>
                        ))}
                      </div>
                      <p className="text-xs text-orange-500 mt-3 font-medium">⚠️ Save these credentials — password is shown only once.</p>
                    </motion.div>
                  )}
                </AnimatePresence>
              </div>
            )}

            {/* ===== BULK UPLOAD ===== */}
            {activeTab === "Bulk Upload" && (
              <div className="max-w-md">
                <div className="bg-card border border-border rounded-2xl p-6">
                  <h2 className="font-bold text-lg mb-1 flex items-center gap-2">
                    <FileUp className="w-5 h-5 text-primary" />Bulk User Import
                  </h2>
                  <p className="text-xs text-foreground/60 mb-5">Upload a CSV file with columns: <code className="bg-secondary px-1 rounded">full_name, email</code></p>
                  
                  <form onSubmit={handleBulkUpload} className="space-y-4">
                    <div>
                      <label className="text-xs font-bold text-foreground/60 mb-1.5 block">Select User Role</label>
                      <div className="grid grid-cols-2 gap-2">
                        {['STUDENT', 'INSTRUCTOR'].map(r => (
                          <button key={r} type="button" onClick={() => setBulkRole(r)}
                            className={`py-2 rounded-xl text-xs font-bold border transition-all ${bulkRole === r ? 'bg-primary text-white border-primary shadow-lg shadow-primary/20' : 'bg-card border-border text-foreground/60'}`}>
                            {r}
                          </button>
                        ))}
                      </div>
                    </div>

                    <div className="border-2 border-dashed border-border rounded-2xl p-8 flex flex-col items-center justify-center gap-3 hover:border-primary/50 transition-all bg-secondary/10">
                      <Upload className="w-8 h-8 text-foreground/20" />
                      <input type="file" accept=".csv" onChange={e => setBulkFile(e.target.files?.[0] || null)} className="text-xs file:hidden cursor-pointer" />
                      <p className="text-[10px] text-foreground/40 font-medium">{bulkFile ? bulkFile.name : "No file selected (CSV only)"}</p>
                    </div>

                    <button type="submit" className={btnClass} disabled={submitting}>
                      <FileUp className="w-4 h-4" /> Start Bulk Import
                    </button>
                  </form>
                </div>
              </div>
            )}
            {activeTab === "Courses" && (
              <div className="grid lg:grid-cols-2 gap-6">
                <div className="bg-card border border-border rounded-2xl p-6">
                  <h3 className="font-bold mb-4 flex items-center gap-2"><Plus className="w-4 h-4 text-primary" />Create New Course</h3>
                  <form onSubmit={handleAddCourse} className="space-y-3">
                    <input className={fieldClass} placeholder="Course Title" value={courseForm.title} onChange={e => setCourseForm(p => ({ ...p, title: e.target.value }))} required />
                    <textarea className={fieldClass} placeholder="Course Description" rows={3} value={courseForm.description} onChange={e => setCourseForm(p => ({ ...p, description: e.target.value }))} required />
                    <select className={fieldClass} value={courseForm.instructor} onChange={e => setCourseForm(p => ({ ...p, instructor: e.target.value }))} required>
                      <option value="">Assign Instructor</option>
                      {instructors.map((u: any) => <option key={u.id} value={u.id}>{u.username}</option>)}
                    </select>
                    <button type="submit" className={btnClass} disabled={submitting}><Plus className="w-4 h-4" />Create & Assign Course</button>
                  </form>
                </div>
                <div className="space-y-3 max-h-[500px] overflow-y-auto">
                  {courses.map((c: any) => (
                    <motion.div key={c.id} whileHover={{ y: -2 }}
                      className="bg-card border border-border rounded-2xl p-4 flex items-start justify-between gap-3">
                      <div className="flex-grow min-w-0">
                        <button onClick={() => setViewingCourse(c)} className="font-semibold text-sm truncate hover:text-accent transition-colors block text-left w-full">
                          {c.title}
                        </button>
                        <button onClick={() => {
                          const inst = instructors.find((i: any) => i.id === c.instructor || i.username === c.instructor_name);
                          if (inst) setViewingUser(inst);
                        }} className="text-xs text-foreground/60 mt-1 hover:text-primary transition-colors underline decoration-primary/30 underline-offset-2">
                          Instructor: {c.instructor_name}
                        </button>
                        <p className="text-xs text-foreground/40 mt-1">Enrollments: {enrollments.filter((e: any) => e.course === c.id).length}</p>
                      </div>
                      <div className="flex items-center gap-1.5 flex-shrink-0">
                        <button onClick={() => setViewingCourse(c)} className="text-accent hover:bg-accent/10 p-1.5 rounded-lg transition-all" title="View Course Details">
                          <Eye className="w-4 h-4" />
                        </button>
                        <button onClick={() => handleDeleteCourse(c.id)} className="text-red-400 hover:text-red-600 p-1.5 rounded-lg hover:bg-red-50 dark:hover:bg-red-900/20 transition-all">
                          <Trash2 className="w-4 h-4" />
                        </button>
                      </div>
                    </motion.div>
                  ))}
                  {courses.length === 0 && <p className="text-foreground/50 text-sm text-center py-8">No courses yet.</p>}
                </div>
              </div>
            )}

            {/* ===== ASSIGN COURSE ===== */}
            {activeTab === "Assign Course" && (
              <div className="max-w-md">
                <div className="bg-card border border-border rounded-2xl p-6">
                  <h2 className="font-bold text-lg mb-1 flex items-center gap-2">
                    <LinkIcon className="w-5 h-5 text-accent" />Assign Student to Course
                  </h2>
                  <p className="text-xs text-foreground/60 mb-5">Enroll any student into any course directly from this panel.</p>
                  <form onSubmit={handleAssignCourse} className="space-y-3">
                    <select className={fieldClass} value={assignForm.student} onChange={e => setAssignForm(p => ({ ...p, student: e.target.value }))} required>
                      <option value="">Select Student</option>
                      {students.map((u: any) => <option key={u.id} value={u.id}>{u.username} ({u.email})</option>)}
                    </select>
                    <select className={fieldClass} value={assignForm.course} onChange={e => setAssignForm(p => ({ ...p, course: e.target.value }))} required>
                      <option value="">Select Course</option>
                      {courses.map((c: any) => <option key={c.id} value={c.id}>{c.title}</option>)}
                    </select>
                    <button type="submit" className={btnClass} disabled={submitting}>
                      <Check className="w-4 h-4" />Enroll Student
                    </button>
                  </form>
                </div>

                {/* Enrollment Overview */}
                <div className="mt-4 bg-card border border-border rounded-2xl overflow-hidden">
                  <div className="px-5 py-3 border-b border-border bg-accent/5">
                    <h3 className="font-bold text-sm">Current Enrollments ({enrollments.length})</h3>
                  </div>
                  <div className="divide-y divide-border max-h-64 overflow-y-auto">
                    {enrollments.length === 0 && <p className="p-4 text-sm text-foreground/50 text-center italic">No enrollments yet.</p>}
                    {enrollments.map((e: any) => (
                      <div key={e.id} className="flex items-center justify-between px-5 py-2.5 text-xs hover:bg-secondary/30 transition-colors">
                        <span className="font-semibold text-foreground/80">{e.student_name}</span>
                        <span className="text-foreground/50">→</span>
                        <span className="text-foreground/60 truncate max-w-32">{e.course_name}</span>
                        <span className="text-primary font-bold">{e.progress}%</span>
                      </div>
                    ))}
                  </div>
                </div>
              </div>
            )}

          </motion.div>
        </AnimatePresence>

        {/* ── QUICK VIEW MODALS ── */}
        <AnimatePresence>
          {viewingUser && (
            <motion.div initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }}
              className="fixed inset-0 z-50 bg-black/60 backdrop-blur-sm flex items-center justify-center p-4">
              <motion.div initial={{ scale: 0.95, y: 20 }} animate={{ scale: 1, y: 0 }}
                className="bg-card border border-border rounded-3xl p-8 w-full max-w-2xl shadow-2xl relative">
                <button onClick={() => setViewingUser(null)} className="absolute top-6 right-6 p-2 rounded-xl hover:bg-secondary/50 transition-all"><X className="w-5 h-5" /></button>
                
                <div className="flex items-center gap-4 mb-8">
                  <div className={`w-16 h-16 rounded-2xl flex items-center justify-center text-2xl font-black ${viewingUser.role === 'INSTRUCTOR' ? 'bg-blue-500/20 text-blue-500' : 'bg-green-500/20 text-green-500'}`}>
                    {viewingUser.username[0].toUpperCase()}
                  </div>
                  <div>
                    <h3 className="text-2xl font-black">{viewingUser.full_name || viewingUser.username}</h3>
                    <p className="text-foreground/60 font-semibold">{viewingUser.role} · {viewingUser.email}</p>
                  </div>
                </div>

                <div className="space-y-4">
                  <h4 className="text-sm font-bold uppercase tracking-widest text-foreground/40 mb-2">
                    {viewingUser.role === 'INSTRUCTOR' ? 'Taught Courses' : 'Enrolled Courses'}
                  </h4>
                  <div className="grid sm:grid-cols-2 gap-3 max-h-64 overflow-y-auto pr-2 scrollbar-thin">
                    {(viewingUser.role === 'INSTRUCTOR' 
                      ? courses.filter(c => c.instructor === viewingUser.id)
                      : enrollments.filter(e => e.student === viewingUser.id)
                    ).map((item: any) => (
                      <div key={item.id} className="p-4 bg-secondary/30 border border-border rounded-2xl flex items-center gap-3">
                        <BookOpen className="w-4 h-4 text-primary" />
                        <span className="text-sm font-bold truncate">{item.title || item.course_name}</span>
                      </div>
                    ))}
                    {(viewingUser.role === 'INSTRUCTOR' 
                      ? courses.filter(c => c.instructor === viewingUser.id)
                      : enrollments.filter(e => e.student === viewingUser.id)
                    ).length === 0 && <p className="col-span-2 text-center py-8 text-foreground/40 italic">No courses found.</p>}
                  </div>
                </div>
              </motion.div>
            </motion.div>
          )}

          {viewingCourse && (
            <motion.div initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }}
              className="fixed inset-0 z-50 bg-black/60 backdrop-blur-sm flex items-center justify-center p-4">
              <motion.div initial={{ scale: 0.95, y: 20 }} animate={{ scale: 1, y: 0 }}
                className="bg-card border border-border rounded-3xl p-8 w-full max-w-2xl shadow-2xl relative">
                <button onClick={() => setViewingCourse(null)} className="absolute top-6 right-6 p-2 rounded-xl hover:bg-secondary/50 transition-all"><X className="w-5 h-5" /></button>
                
                <div className="mb-8">
                  <div className="inline-block px-3 py-1 rounded-lg bg-primary/10 text-primary text-xs font-black uppercase tracking-widest mb-2">Course Detail</div>
                  <h3 className="text-3xl font-black">{viewingCourse.title}</h3>
                  <p className="text-foreground/60 mt-2 font-medium">{viewingCourse.description}</p>
                </div>

                <div className="grid sm:grid-cols-2 gap-8">
                  <div>
                    <h4 className="text-sm font-bold uppercase tracking-widest text-foreground/40 mb-3">Instructor</h4>
                    <div className="p-4 bg-blue-500/5 border border-blue-500/20 rounded-2xl flex items-center gap-3">
                      <div className="w-10 h-10 rounded-xl bg-blue-500/20 text-blue-500 flex items-center justify-center font-bold">
                        {viewingCourse.instructor_name?.[0] || 'I'}
                      </div>
                      <span className="font-bold">{viewingCourse.instructor_name}</span>
                    </div>
                  </div>
                  <div>
                    <h4 className="text-sm font-bold uppercase tracking-widest text-foreground/40 mb-3">Enrolled Students ({enrollments.filter(e => e.course === viewingCourse.id).length})</h4>
                    <div className="space-y-2 max-h-48 overflow-y-auto pr-2 scrollbar-thin">
                      {enrollments.filter(e => e.course === viewingCourse.id).map((e: any) => (
                        <div key={e.id} className="p-3 bg-green-500/5 border border-green-500/20 rounded-xl flex items-center gap-3">
                          <GraduationCap className="w-4 h-4 text-green-500" />
                          <span className="text-sm font-medium">{e.student_name}</span>
                        </div>
                      ))}
                      {enrollments.filter(e => e.course === viewingCourse.id).length === 0 && <p className="text-xs text-foreground/40 italic py-4">No students enrolled yet.</p>}
                    </div>
                  </div>
                </div>
              </motion.div>
            </motion.div>
          )}
        </AnimatePresence>

      </div>
    </div>
  );
}
